# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Replay Table
lang: en
description: >
  A script that transforms a csv file with season results into interactive standings.
baseurl: ""
url: "https://replaytable.com"

script_prod: "//cdn.jsdelivr.net/replay-table/latest/replay-table.min.js"
css_prod: "//cdn.jsdelivr.net/replay-table/latest/replay-table.css"
script_dev: "https://rawgit.com/TargetProcess/replayTable/master/dist/replay-table.min.js"
css_dev: "https://rawgit.com/TargetProcess/replayTable/master/dist/replay-table.css"

# Build settings
encoding: utf-8
highlighter: rouge
future: true
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tables:
    output: true
  posts:
    output: true
    permalink: /blog/:title

defaults:
  -
    scope:
      path: ""
      type: "tables"
    values:
      layout: "table"