# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Replay Table. Interactive season standings
lang: en
description: A library for visualizing sport season results with interactive standings.
baseurl: "/replay"
url: "https://antoniokov.com/replay"

script_prod: "https://unpkg.com/replay-table/dist/replay-table.min.js"
css_prod: "https://unpkg.com/replay-table/dist/replay-table.css"
script_dev: "https://raw.githubusercontent.com/antoniokov/replay-table/master/dist/replay-table.min.js"
css_dev: "https://raw.githubusercontent.com/antoniokov/replay-table/master/dist/replay-table.css"

repository: "antoniokov/replay"

# Build settings
encoding: utf-8
highlighter: rouge
future: true
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tables:
    output: true
  posts:
    output: true
    permalink: /blog/:title

defaults:
  -
    scope:
      path: ""
      type: "tables"
    values:
      layout: "table"